name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev aidl
          pip install --upgrade pip
          pip install buildozer cython
      - name: Build
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: ${{ steps.buildozer.outputs.filename }}
